"""create initial schema

Creates all 7 tables. Autogenerated, then edited by hand in one place:
autogenerate rendered every enum CHECK constraint three times (an explicit
CheckConstraint with a raw name, one with the convention name, and one more
from sa.Enum(create_constraint=True)). We keep only the convention-named
CheckConstraint and set create_constraint=False on the Enum columns, so each
rule exists exactly once. See docs/LEARNING_LOG.md, Phase 1.

Revision ID: 6d77ffc5b43e
Revises: 
Create Date: 2026-10-06 20:34:04.404766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d77ffc5b43e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_color', sa.String(length=7), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('personal_meeting_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('personal_meeting_id', name=op.f('uq_users_personal_meeting_id'))
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_code', sa.String(length=11), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('instant', 'scheduled', 'personal', name='meeting_type', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', 'cancelled', name='meeting_status', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('passcode', sa.String(length=10), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'ended', 'cancelled')", name=op.f('ck_meetings_meeting_status')),
    sa.CheckConstraint("type IN ('instant', 'scheduled', 'personal')", name=op.f('ck_meetings_meeting_type')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_meetings_duration_positive')),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_meetings_host_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings')),
    sa.UniqueConstraint('invite_token', name=op.f('uq_meetings_invite_token')),
    sa.UniqueConstraint('meeting_code', name=op.f('uq_meetings_meeting_code'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_host_id_start_time', ['host_id', 'start_time'], unique=False)
        batch_op.create_index('ix_meetings_status', ['status'], unique=False)

    op.create_table('meeting_invitees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_invitees_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_invitees')),
    sa.UniqueConstraint('meeting_id', 'email', name=op.f('uq_meeting_invitees_meeting_id_email'))
    )
    op.create_table('meeting_settings',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('waiting_room_enabled', sa.Boolean(), nullable=False),
    sa.Column('mute_on_entry', sa.Boolean(), nullable=False),
    sa.Column('video_on_entry_host', sa.Boolean(), nullable=False),
    sa.Column('video_on_entry_participant', sa.Boolean(), nullable=False),
    sa.Column('allow_join_before_host', sa.Boolean(), nullable=False),
    sa.Column('allow_screen_share', sa.Enum('host_only', 'all', name='screen_share_permission', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("allow_screen_share IN ('host_only', 'all')", name=op.f('ck_meeting_settings_screen_share_permission')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_settings_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_meeting_settings'))
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('host', 'co_host', 'attendee', name='participant_role', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'admitted', 'left', 'removed', name='participant_status', native_enum=False, create_constraint=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('host', 'co_host', 'attendee')", name=op.f('ck_participants_participant_role')),
    sa.CheckConstraint("status IN ('waiting', 'admitted', 'left', 'removed')", name=op.f('ck_participants_participant_status')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_participants_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participants_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('ix_participants_meeting_id_status', ['meeting_id', 'status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('sender_participant_id', sa.Integer(), nullable=False),
    sa.Column('recipient_participant_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_chat_messages_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_participant_id'], ['participants.id'], name=op.f('fk_chat_messages_recipient_participant_id_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['participants.id'], name=op.f('fk_chat_messages_sender_participant_id_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_meeting_id_sent_at', ['meeting_id', 'sent_at'], unique=False)

    op.create_table('meeting_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_events_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_meeting_events_participant_id_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_events'))
    )
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_events_meeting_id_created_at', ['meeting_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_events_meeting_id_created_at')

    op.drop_table('meeting_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_meeting_id_sent_at')

    op.drop_table('chat_messages')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_meeting_id_status')

    op.drop_table('participants')
    op.drop_table('meeting_settings')
    op.drop_table('meeting_invitees')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_status')
        batch_op.drop_index('ix_meetings_host_id_start_time')

    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
