"""add accounts: password hash and sign-in sessions

Adds users.password_hash and the auth_sessions table (one row per signed-in browser).
Autogenerated, plus one hand-written step: accounts that existed before login (the demo
accounts) get the demo password, so an existing database can still log in.

Revision ID: a0bb0d0a6bb5
Revises: e8f24579607c
Create Date: 2026-10-07 12:03:39.607647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bb0d0a6bb5'
down_revision: Union[str, Sequence[str], None] = 'e8f24579607c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEMO_PASSWORD_HASH = (
    "scrypt$16384$8$1$4c5c1f62c5c9f28469e67d844bad323c$"
    "98033f5805b5fc2f259789b71de39570b9cb5dd87a7a0d52673c8df4e83fe913"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # Hand-added: before this migration every account was a seeded demo account, so they
    # all get the demo password ("demo1234"). This is its scrypt hash, written out here
    # because a migration must not import app code that may change later.
    op.execute(
        sa.text("UPDATE users SET password_hash = :demo_hash WHERE password_hash IS NULL")
        .bindparams(demo_hash=DEMO_PASSWORD_HASH)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
