"""add users.email_verified

Whether an account's email is proven. Only verified accounts see meetings they're invited
to (sign-up can't verify an address, so new accounts start unverified). Autogenerated,
plus one hand-written step: the seeded demo accounts are marked verified, as a fresh
seed creates them.

Revision ID: edc2f38ff234
Revises: a0bb0d0a6bb5
Create Date: 2026-10-07 12:47:50.861811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc2f38ff234'
down_revision: Union[str, Sequence[str], None] = 'a0bb0d0a6bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEMO_ACCOUNT_EMAILS = [
    "alex.morgan@example.com",
    "priya.sharma@example.com",
    "daniel.kim@example.com",
    "sofia.rossi@example.com",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###

    # Hand-added: the demo accounts (listed here, because a migration must not import app
    # code that may change later). Accounts people signed up with stay unverified.
    op.execute(
        sa.text("UPDATE users SET email_verified = 1 WHERE email IN :emails").bindparams(
            sa.bindparam("emails", value=DEMO_ACCOUNT_EMAILS, expanding=True)
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
