"""add session token and recurrence

Adds participants.session_token (proves who owns a WebSocket connection) and
meetings.recurrence (a "repeats daily/weekly" label). Autogenerated; the downgrade was
edited by hand (see the comment there and docs/LEARNING_LOG.md, Phase 4).

Revision ID: e8f24579607c
Revises: 6d77ffc5b43e
Create Date: 2026-10-06 21:24:06.816566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f24579607c'
down_revision: Union[str, Sequence[str], None] = '6d77ffc5b43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.Enum('none', 'daily', 'weekly', name='recurrence', native_enum=False, create_constraint=True), server_default='none', nullable=False))

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_participants_session_token'), ['session_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_participants_session_token'), type_='unique')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        # Hand-added: drop the CHECK on `recurrence` before the column itself. Otherwise
        # the rebuilt table keeps a CHECK that names a column that no longer exists, and
        # SQLite fails with "no such column: recurrence".
        batch_op.drop_constraint(op.f('ck_meetings_recurrence'), type_='check')
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
